apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: database
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
