apiVersion: v1
kind: Secret
metadata:
  name: cluster-vars
  namespace: flux-system
stringData:
  POSTGRES_DB: "${PG_DB}"
  POSTGRES_USER: "${PG_USER}"
  POSTGRES_PASSWORD: "${PG_PASSWORD}"
  PG_STORAGE: "${PG_STORAGE}"
  BACKUP_SCHEDULE: "${BACKUP_SCHEDULE}"
  BACKUP_RETAIN_DAYS: "${BACKUP_RETAIN_DAYS}"
  LE_EMAIL: "${LE_EMAIL}"
  DOMAIN: "${DOMAIN}"
